source 'https://github.com/CocoaPods/Specs.git'


target 'UserKVStorage_Example' do
  use_frameworks!
  inhibit_all_warnings!
  platform :ios, '11.0'

  pod 'UserKVStorage', :path => '../'

  target 'UserKVStorage_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
